#服务设置
Server:
  #服务地址
  Host: "0.0.0.0"
  #服务端口
  Port: 33214
  #Websocket设置
  Websocket:
    #端口
    Port: 33215

#设置
Set:
  #重置密码间隔时间(单位: ms)
  ResetTime: 1800000
  #日期格式
  DateFormat: "yyyy/MM/dd-HH:mm:ss"
  #存储方式(MYSQL/SQLite)
  Data: "MYSQL"
  #JSON不需要额外设置
  #MYSQL设置
  Mysql:
    #数据库地址
    Host: "jdbc:mysql://localhost"
    #数据库端口
    Port: "3306"
    #数据库名称
    Database: "secure"
    #数据库用户
    Username: "root"
    #数据库密码
    Password: "root"
    #失败重连次数
    ReconnectTime: 10
    #失败重连尝试延迟
    ReconnectDelay: 3
  #SQLite设置
  SQLite:
    #文件路径
    Path: "secure.db"